addons:
  code_climate:
    repo_token: 31b1d4016ea2c5a825f57bea4460a7b07dfe9685c4101f2011585226061b9208
sudo: false
os:
  - linux
language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
script:
  - make
after_success:
  - pip install codeclimate-test-reporter
  - codeclimate-test-reporter
